removeAnvilLimit = true
allowAllEnchantmentCombinations = false
allowAnyEnchantOnAnyItem = false
useGlobalEnchantCap = true
globalEnchantCap = 10
protectionCap = 4
protectionFireCap = 4
protectionBlastCap = 4
protectionProjectileCap = 4
respirationCap = 3
thornsCap = 3
frostWalkerCap = 2
soulSpeedCap = 3
depthStriderCap = 3
featherFallingCap = 4
smiteCap = 5
sharpnessCap = 5
baneOfArthropodsCap = 5
knockbackCap = 2
fireAspectCap = 2
lootingCap = 3
sweepingCap = 3
efficiencyCap = 5
fortuneCap = 3
powerCap = 5
punchCap = 2
lureCap = 3
luckOfTheSeaCap = 3
impalingCap = 5
loyaltyCap = 3
quickChargeCap = 3
piercingCap = 4
unbreakingCap = 3
